version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=liverpool
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - ./pgvolume:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    command: ["/go/src/app/bin/enlabs"]
    ports:
      - "8001:8001"