[service]
    http = "8001"
    cancellationTimeout = 1 # minutes between canceling last 10 transactions

[postgres]
    dsn = "host=enlabs-test_db_1 port=5432 user=postgres password=liverpool dbname=test sslmode=disable"